name: 📦 Build
run-name: 📦 Build triggered
on: push
jobs:
  build:
    name: lccmrx.com build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@master

      - name: install node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: install app dependencies
        run: yarn

      - name: building app
        run: yarn build

      - name: uploading to S3
        run: |
          aws s3 sync ./public s3://lccmrx-www
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
          AWS_DEFAULT_REGION: sa-east-1

      - name: Invalidate cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: EM6R82I0HZHV7
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
